export const cvDownloadUrl = '/docs/CV_SEUNGJILEE.pdf'
export const cvFileName = 'CV_SEUNGJILEE.pdf'
export const email = 'sandyleedev@gmail.com'
export const githubUrl = 'https://github.com/sandyleedev'
export const linkedInUrl = 'https://www.linkedin.com/in/seungjilee/'
export const instagramUrl = 'https://www.instagram.com/dltmdwl'